# Generated by Django 6.0.5 on 2026-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_mode',
            field=models.CharField(choices=[('signup', 'Signup Mode'), ('credit_check', 'Credit Check Mode'), ('offer_service', 'Offer Service Mode'), ('lend_money', 'Lend Money Mode'), ('track_lended', 'Track Lended Mode'), ('settle_debt', 'Settle Debt Mode'), ('welcome', 'Welcome Mode')], default='welcome', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_status',
            field=models.CharField(choices=[('national_id', 'Awaiting National ID'), ('otp_confirmation', 'Awaiting OTP Confirmation'), ('full_name', 'Awaiting Full Name'), ('phone_verification', 'Awaiting Phone Verification'), ('borrower_id', 'Awaiting Borrower National ID'), ('borrower_phone', 'Awaiting Borrower Phone Number'), ('credit_review', 'Viewing Credit History'), ('lend_amount', 'Entering Lend Amount'), ('settlement_confirmation', 'Confirming Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('welcome', 'Welcome State')], default='welcome', max_length=50),
        ),
    ]
