# Generated by Django 6.0.5 on 2026-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_person_user_mode_alter_person_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='mentioned_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='oldest_creditor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
