# Generated by Django 6.0.5 on 2026-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_amount_owed_person_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mentioned_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='old_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_mode',
            field=models.CharField(choices=[('signup', 'Signup Mode'), ('credit_check', 'Credit Check Mode'), ('offer_service', 'Offer Service Mode'), ('lend_money', 'Lend Money Mode'), ('track_lended', 'Track Lended Mode'), ('settle_debt', 'Settle Debt Mode'), ('welcome', 'Welcome Mode'), ('verification_hold', 'Verification Hold')], default='welcome', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_status',
            field=models.CharField(choices=[('national_id', 'Awaiting National ID'), ('otp_confirmation', 'Awaiting OTP Confirmation'), ('full_name', 'Awaiting Full Name'), ('phone_number', 'Awaiting Phone Number'), ('phone_verification', 'Awaiting Phone Verification'), ('borrower_id', 'Awaiting Borrower National ID'), ('borrower_phone', 'Awaiting Borrower Phone Number'), ('credit_review', 'Viewing Credit History'), ('lend_amount', 'Entering Lend Amount'), ('settlement_confirmation', 'Confirming Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('welcome', 'Welcome State'), ('hold', 'Hold Access')], default='welcome', max_length=50),
        ),
    ]
