# Generated by Django 6.0.5 on 2026-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_person_mentioned_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('hold', 'Verification Hold'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20),
        ),
    ]
