# Generated by Django 6.0.5 on 2026-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_person_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
