# Generated by Django 6.0.5 on 2026-07-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_persons', to='users.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_mode',
            field=models.CharField(choices=[('signup', 'Signup Mode'), ('edit_profile', 'Edit Profile Mode'), ('credit_check', 'Credit Check Mode'), ('offer_service', 'Offer Service Mode'), ('lend_money', 'Lend Money Mode'), ('track_lended', 'Track Lended Mode'), ('settle_debt', 'Settle Debt Mode'), ('welcome', 'Welcome Mode'), ('verification_hold', 'Verification Hold'), ('add_subject', 'Add Subject')], default='welcome', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_status',
            field=models.CharField(choices=[('national_id', 'Awaiting National ID'), ('otp_confirmation', 'Awaiting OTP Confirmation'), ('full_name', 'Awaiting Full Name'), ('add_address', 'Adding Address'), ('edit_address', 'Editing Address'), ('edit_phone_number', 'Editing Phone Number'), ('edit_national_id', 'Editing National ID'), ('edit_full_name', 'Editing Full Name'), ('phone_number', 'Awaiting Phone Number'), ('phone_verification', 'Awaiting Phone Verification'), ('borrower_id', 'Awaiting Borrower National ID'), ('borrower_phone', 'Awaiting Borrower Phone Number'), ('credit_review', 'Viewing Credit History'), ('lend_amount', 'Entering Lend Amount'), ('settlement_confirmation', 'Confirming Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('welcome', 'Welcome State'), ('hold', 'Hold Access'), ('verify_details', 'Verifying Details')], default='welcome', max_length=50),
        ),
    ]
