# Generated by Django 6.0.5 on 2026-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_person_user_mode_alter_person_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_mode',
            field=models.CharField(choices=[('signup', 'Signup Mode'), ('borrower_signup', 'Borrower Signup Mode'), ('login', 'Login Mode'), ('edit_profile', 'Edit Profile Mode'), ('edit_borrower', 'Edit Borrower Mode'), ('credit_check', 'Credit Check Mode'), ('offer_service', 'Offer Service Mode'), ('lend_money', 'Lend Money Mode'), ('track_lended', 'Track Lended Mode'), ('settle_debt', 'Settle Debt Mode'), ('welcome', 'Welcome Mode'), ('verification_hold', 'Verification Hold'), ('add_subject', 'Add Subject'), ('borrower_confirmation', 'Borrower Confirmation'), ('suspension', 'Suspended'), ('addition_aborted', 'Addition Aborted')], default='welcome', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_status',
            field=models.CharField(choices=[('national_id', 'Awaiting National ID'), ('otp_confirmation', 'Awaiting OTP Confirmation'), ('otp_setup', 'Awaiting OTP Setup'), ('full_name', 'Awaiting Full Name'), ('add_address', 'Adding Address'), ('edit_address', 'Editing Address'), ('edit_phone_number', 'Editing Phone Number'), ('edit_national_id', 'Editing National ID'), ('edit_full_name', 'Editing Full Name'), ('phone_number', 'Awaiting Phone Number'), ('phone_verification', 'Awaiting Phone Verification'), ('request_borrower_info', 'Requesting Borrower Payment Information'), ('borrower_id', 'Awaiting Borrower National ID'), ('borrower_phone', 'Awaiting Borrower Phone Number'), ('borrower_full_name', 'Awaiting Borrower Full Name'), ('borrower_address', 'Awaiting Borrower Address'), ('credit_review', 'Viewing Credit History'), ('lend_amount', 'Entering Lend Amount'), ('settlement_confirmation', 'Confirming Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('welcome', 'Welcome State'), ('hold', 'Hold Access'), ('verify_details', 'Verifying Details'), ('verify_borrower_details', 'Verifying Borrower')], default='welcome', max_length=50),
        ),
    ]
