# Generated by Django 6.0.5 on 2026-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_person_user_mode_alter_person_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_status',
            field=models.CharField(choices=[('national_id', 'Awaiting National ID'), ('otp_confirmation', 'Awaiting OTP Confirmation'), ('otp_setup', 'Awaiting OTP Setup'), ('full_name', 'Awaiting Full Name'), ('add_address', 'Adding Address'), ('edit_address', 'Editing Address'), ('edit_phone_number', 'Editing Phone Number'), ('edit_national_id', 'Editing National ID'), ('edit_full_name', 'Editing Full Name'), ('phone_number', 'Awaiting Phone Number'), ('phone_verification', 'Awaiting Phone Verification'), ('request_borrower_info', 'Requesting Borrower Payment Information'), ('borrower_id', 'Awaiting Borrower National ID'), ('borrower_phone', 'Awaiting Borrower Phone Number'), ('give_credit', 'Awaiting Credit Details'), ('borrower_full_name', 'Awaiting Borrower Full Name'), ('borrower_address', 'Awaiting Borrower Address'), ('credit_review', 'Viewing Credit History'), ('lend_amount', 'Entering Lend Amount'), ('settlement_confirmation', 'Confirming Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('welcome', 'Welcome State'), ('hold', 'Hold Access'), ('verify_details', 'Verifying Details'), ('verify_borrower_details', 'Verifying Borrower'), ('enter_credit_currency', 'Enter Currency'), ('enter_credit_amount', 'Enter Credit Amount'), ('enter_credit_type', 'Enter Credit Type'), ('enter_end_date', 'Enter End Date'), ('confirm_credit_details', 'Confirm Credit'), ('accept_credit', 'Accept Credit'), ('enter_receipt_amount', 'Enter Receipt Amount'), ('enter_receipt_currency', 'Enter Receipt Currency'), ('receipting', 'Receipting'), ('receipted', 'Receipted'), ('receipt_confirmation', 'Receipt Confirmation'), ('receipt_confirmed', 'Receipt Confirmed'), ('receipt_date', 'Receipt Date'), ('offer_lending', 'Offer Lending')], default='welcome', max_length=50),
        ),
    ]
