# Generated by Django 6.0.5 on 2026-05-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('content', models.TextField()),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.person')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['person', 'timestamp'], name='chatbot_wha_person__7b98f9_idx')],
            },
        ),
    ]
