# Generated by Django 6.0.5 on 2026-05-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('self_check', 'Self Check'), ('third_party', 'Third Party Check')], max_length=20)),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP Verification'), ('otp_sent', 'OTP Sent'), ('verified', 'Verified'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending_otp', max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('credit_history_snapshot', models.JSONField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_made', to='users.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_received', to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCheckAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('performed_by_phone', models.CharField(max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='credit.creditcheck')),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField()),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_risk', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_histories', to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='LendingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('defaulted', 'Defaulted'), ('disputed', 'Disputed')], default='active', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_taken', to='users.person')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_given', to='users.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='creditcheck',
            index=models.Index(fields=['checker', 'status'], name='credit_cred_checker_c53c51_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcheck',
            index=models.Index(fields=['subject', 'created_at'], name='credit_cred_subject_89c9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcheck',
            index=models.Index(fields=['otp_code', 'status'], name='credit_cred_otp_cod_43b656_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcheckaudit',
            index=models.Index(fields=['credit_check', 'created_at'], name='credit_cred_credit__d18f99_idx'),
        ),
        migrations.AddIndex(
            model_name='lendingcontract',
            index=models.Index(fields=['lender', 'status'], name='credit_lend_lender__02d219_idx'),
        ),
        migrations.AddIndex(
            model_name='lendingcontract',
            index=models.Index(fields=['borrower', 'status'], name='credit_lend_borrowe_0bca42_idx'),
        ),
        migrations.AddIndex(
            model_name='lendingcontract',
            index=models.Index(fields=['due_date'], name='credit_lend_due_dat_7db0e4_idx'),
        ),
    ]
