# Generated by Django 6.0.5 on 2026-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='total_claims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credithistory',
            name='total_courts',
            field=models.IntegerField(default=0),
        ),
    ]
