# Generated by Django 6.0.5 on 2026-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credithistory_total_claims_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingcontract',
            name='credit_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('goods', 'Goods'), ('service', 'Service'), ('loan', 'Loan'), ('mukando', 'Mukando')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lendingcontract',
            name='currency',
            field=models.CharField(choices=[('rand', 'ZAR'), ('usd', 'USD'), ('zwl', 'ZWL')], default='usd', max_length=5),
        ),
        migrations.AddField(
            model_name='lendingcontract',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lendingcontract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('defaulted', 'Defaulted'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
