# Generated by Django 6.0.5 on 2026-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_lendingcontract_credit_type_lendingcontract_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingcontract',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
