# Generated by Django 6.0.5 on 2026-08-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_alter_lendingcontract_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingcontract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('defaulted', 'Defaulted'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('rand', 'ZAR'), ('usd', 'USD'), ('zwl', 'ZWL')], default='usd', max_length=5)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lending_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='credit.lendingcontract')),
            ],
            options={
                'indexes': [models.Index(fields=['lending_contract', 'confirmed'], name='credit_rece_lending_0f7ef5_idx'), models.Index(fields=['receipt_date'], name='credit_rece_receipt_f7fba6_idx')],
            },
        ),
    ]
