# Generated by Django 6.0.5 on 2026-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_lendingcontract_status_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingcontract',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
