# Generated by Django 6.0.5 on 2026-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_alter_lendingcontract_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
