# Generated by Django 6.0.5 on 2026-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingcontract',
            name='instalment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lendingcontract',
            name='lodge_date',
            field=models.DateField(blank=True, help_text='Date the loan was put in the system', null=True),
        ),
        migrations.AlterField(
            model_name='creditcheck',
            name='status',
            field=models.CharField(choices=[('pending_otp', 'Pending OTP Verification'), ('otp_sent', 'OTP Sent'), ('verified', 'Verified'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending_otp', max_length=20),
        ),
    ]
