# Generated by Django 6.0.5 on 2026-08-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_lendingcontract_instalment_amount_and_more'),
        ('users', '0014_user_is_client_user_alter_user_role_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingcontract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='users.company'),
        ),
    ]
