# Generated by Django 6.0.5 on 2026-09-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_lendingcontract_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingcontract',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date the loan starts', null=True),
        ),
    ]
