# Generated by Django 6.0.5 on 2026-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0010_lendingcontract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingcontract',
            name='agreement_number',
            field=models.CharField(blank=True, help_text='Unique agreement number for the contract', max_length=50, null=True),
        ),
    ]
